server:
  port: 0

spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: org.example.event.UserEvent:org.example.notificationservice.event.UserEvent
        spring.json.trusted.packages: "*"

  mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.learn.notificationservice: DEBUG
    org.springframework.kafka: DEBUG